name: Spring Boot CI/CD

on:
  push:
    branches:
      - develop  # develop ë¸Œëœì¹˜ì— pushë  ë•Œ ì‹¤í–‰

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“ í”„ë¡œì íŠ¸ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: â˜• JDK 17 ì„¤ì •
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ”“ gradlew ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
        run: chmod +x ./gradlew

      - name: ğŸ› ï¸ Gradleë¡œ ë¹Œë“œ
        run: ./gradlew clean build --no-daemon

      - name: ğŸ³ Docker Buildx ì„¤ì •
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” DockerHub ë¡œê·¸ì¸
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ“¦ Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° í‘¸ì‹œ
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/welibrary-app:latest
